# Generated by Django 2.2.24 on 2022-03-23 12:06

from django.db import migrations


def specify_new_building(apps, schema_editor):
    """
    Указание новостройка или нет
    """
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        if not flat.new_building:
            flat.new_building = flat.construction_year >= 2015
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(specify_new_building),
    ]
