# Generated by Django 2.2.24 on 2022-05-17 09:48

from django.db import migrations


def copy_info_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner_obj, created = Owner.objects.get_or_create(owner=flat.owner)
        owner_obj.owners_phonenumber = flat.owners_phonenumber
        owner_obj.owner_pure_phone = flat.owner_pure_phone
        owner_obj.flat.add(flat)
        owner_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220517_0754'),
    ]

    operations = [
        migrations.RunPython(copy_info_owners),
    ]
